// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for LivenessStatus.
const (
	DOWN LivenessStatus = "DOWN"
	UP   LivenessStatus = "UP"
)

// Defines values for OrderStatus.
const (
	AWAITINGPICKUP OrderStatus = "AWAITING_PICKUP"
	CANCELLED      OrderStatus = "CANCELLED"
	DELIVERED      OrderStatus = "DELIVERED"
	DISPUTED       OrderStatus = "DISPUTED"
	INTRANSIT      OrderStatus = "IN_TRANSIT"
	PENDING        OrderStatus = "PENDING"
	RETURNED       OrderStatus = "RETURNED"
)

// N400 Bad Request
type N400 = interface{}

// N401 Unauthorized
type N401 = interface{}

// N403 Forbidden
type N403 = interface{}

// N404 Not Found
type N404 = interface{}

// N500 Internal Server Error
type N500 = interface{}

// Customer defines model for Customer.
type Customer struct {
	// CreatedAt Created At details
	CreatedAt *time.Time          `json:"created_at,omitempty" validate:"rfc3339_date-time"`
	Email     openapi_types.Email `json:"email" validate:"required,email"`
	Id        uuid.UUID           `json:"id" validate:"required,id"`
	Name      string              `json:"name" validate:"required"`
	Phone     string              `json:"phone" validate:"required,e164"`

	// UpdatedAt Updated At details
	UpdatedAt *time.Time `json:"updated_at,omitempty" validate:"rfc3339_date-time"`
}

// CustomerDetails defines model for CustomerDetails.
type CustomerDetails struct {
	Email openapi_types.Email `json:"email" validate:"required,email"`
	Name  string              `json:"name" validate:"required"`
	Phone string              `json:"phone" validate:"required,e164"`
}

// CustomerIdType CustomerID
type CustomerIdType = uuid.UUID

// Error General API Error Response
type Error struct {
	Code      int        `json:"code"`
	Domain    *string    `json:"domain,omitempty"`
	Message   string     `json:"message"`
	Reason    *string    `json:"reason,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Liveness defines model for Liveness.
type Liveness struct {
	Message *string         `json:"message,omitempty" validate:"required"`
	Status  *LivenessStatus `json:"status,omitempty" validate:"required,oneof=UP DOWN"`
}

// LivenessStatus defines model for Liveness.Status.
type LivenessStatus string

// NewCustomerRequest defines model for NewCustomerRequest.
type NewCustomerRequest struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`
	Phone string              `json:"phone" validate:"e164"`
}

// NewOrderRequest New Order Request details
type NewOrderRequest struct {
	Customer CustomerDetails `json:"customer"`
	Products []NewProduct    `json:"products"`

	// Taxes Order Taxes details
	Taxes *float64 `json:"taxes,omitempty"`

	// Total Order Total details
	Total *float64 `json:"total,omitempty"`
}

// NewProduct defines model for NewProduct.
type NewProduct struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	UnitPrice   float64 `json:"unit_price"`
}

// Order defines model for Order.
type Order struct {
	// CreatedAt Created At details
	CreatedAt *time.Time `json:"created_at,omitempty" validate:"rfc3339_date-time"`
	Customer  Customer   `json:"customer"`
	Id        uuid.UUID  `json:"id" validate:"required,id"`
	Products  []Product  `json:"products"`

	// Status Order Status details
	Status OrderStatus `json:"status" validate:"required,oneof=PENDING AWAITING_PICKUP IN_TRANSIT DELIVERED CANCELLED RETURNED DISPUTED"`

	// Taxes Order Taxes details
	Taxes *float64 `json:"taxes,omitempty"`

	// Total Order Total details
	Total *float64 `json:"total,omitempty"`

	// UpdatedAt Updated At details
	UpdatedAt *time.Time `json:"updated_at,omitempty" validate:"rfc3339_date-time"`
}

// OrderStatus Order Status details
type OrderStatus string

// OrderIdType OrderID
type OrderIdType = uuid.UUID

// Product defines model for Product.
type Product struct {
	// CreatedAt Created At details
	CreatedAt *time.Time `json:"created_at,omitempty" validate:"rfc3339_date-time"`

	// Description Product Description details
	Description *string   `json:"description,omitempty"`
	Id          uuid.UUID `json:"id" validate:"required,id"`

	// Name Product Name details
	Name      string  `json:"name" validate:"required"`
	UnitPrice float64 `json:"unit_price"`

	// UpdatedAt Updated At details
	UpdatedAt *time.Time `json:"updated_at,omitempty" validate:"rfc3339_date-time"`
}

// ProductIdType ProductID
type ProductIdType = uuid.UUID

// XRequestIdType X-RequestID
type XRequestIdType = uuid.UUID

// CustomerID CustomerID
type CustomerID = CustomerIdType

// OrderID OrderID
type OrderID = OrderIdType

// ProductID ProductID
type ProductID = ProductIdType

// XRequestID X-RequestID
type XRequestID = XRequestIdType

// Limit defines model for limit.
type Limit = int

// Page defines model for page.
type Page = int

// GetCustomersParams defines parameters for GetCustomers.
type GetCustomersParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty" schema:"page" validate:"omitempty,gte=0"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty" schema:"limit" validate:"omitempty,gte=0"`

	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// CreateCustomerParams defines parameters for CreateCustomer.
type CreateCustomerParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// DeleteCustomerByIDParams defines parameters for DeleteCustomerByID.
type DeleteCustomerByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// GetCustomerByIDParams defines parameters for GetCustomerByID.
type GetCustomerByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// UpdateCustomerByIDParams defines parameters for UpdateCustomerByID.
type UpdateCustomerByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// GetLivenessParams defines parameters for GetLiveness.
type GetLivenessParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty" schema:"page" validate:"omitempty,gte=0"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty" schema:"limit" validate:"omitempty,gte=0"`

	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// DeleteOrderByIDParams defines parameters for DeleteOrderByID.
type DeleteOrderByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// GetOrderByIDParams defines parameters for GetOrderByID.
type GetOrderByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// UpdateOrderByIDParams defines parameters for UpdateOrderByID.
type UpdateOrderByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// GetProductsParams defines parameters for GetProducts.
type GetProductsParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty" schema:"page" validate:"omitempty,gte=0"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty" schema:"limit" validate:"omitempty,gte=0"`

	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// CreateProductParams defines parameters for CreateProduct.
type CreateProductParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// DeleteProductByIDParams defines parameters for DeleteProductByID.
type DeleteProductByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// GetProductByIDParams defines parameters for GetProductByID.
type GetProductByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// UpdateProductByIDParams defines parameters for UpdateProductByID.
type UpdateProductByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// GetReadinessParams defines parameters for GetReadiness.
type GetReadinessParams struct {
	// XRequestID X-Request-ID
	XRequestID XRequestID `json:"xRequestID"`
}

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = NewCustomerRequest

// UpdateCustomerByIDJSONRequestBody defines body for UpdateCustomerByID for application/json ContentType.
type UpdateCustomerByIDJSONRequestBody = Customer

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = NewOrderRequest

// UpdateOrderByIDJSONRequestBody defines body for UpdateOrderByID for application/json ContentType.
type UpdateOrderByIDJSONRequestBody = Order

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = NewProduct

// UpdateProductByIDJSONRequestBody defines body for UpdateProductByID for application/json ContentType.
type UpdateProductByIDJSONRequestBody = Product

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all customers
	// (GET /customers)
	GetCustomers(c *gin.Context, params GetCustomersParams)
	// Create a new customer
	// (POST /customers)
	CreateCustomer(c *gin.Context, params CreateCustomerParams)
	// Delete a customer
	// (DELETE /customers/{customerID})
	DeleteCustomerByID(c *gin.Context, customerID CustomerID, params DeleteCustomerByIDParams)
	// Get a specific customer by ID
	// (GET /customers/{customerID})
	GetCustomerByID(c *gin.Context, customerID CustomerID, params GetCustomerByIDParams)
	// Update an existing customer
	// (PUT /customers/{customerID})
	UpdateCustomerByID(c *gin.Context, customerID CustomerID, params UpdateCustomerByIDParams)
	// Get liveness status
	// (GET /liveness)
	GetLiveness(c *gin.Context, params GetLivenessParams)
	// Get all orders
	// (GET /orders)
	GetOrders(c *gin.Context, params GetOrdersParams)
	// Create a new order
	// (POST /orders)
	CreateOrder(c *gin.Context, params CreateOrderParams)
	// Delete an order
	// (DELETE /orders/{orderID})
	DeleteOrderByID(c *gin.Context, orderID OrderID, params DeleteOrderByIDParams)
	// Get a specific order by ID
	// (GET /orders/{orderID})
	GetOrderByID(c *gin.Context, orderID OrderID, params GetOrderByIDParams)
	// Update an existing order
	// (PUT /orders/{orderID})
	UpdateOrderByID(c *gin.Context, orderID OrderID, params UpdateOrderByIDParams)
	// Get all products
	// (GET /products)
	GetProducts(c *gin.Context, params GetProductsParams)
	// Create a new product
	// (POST /products)
	CreateProduct(c *gin.Context, params CreateProductParams)
	// Delete a product
	// (DELETE /products/{productID})
	DeleteProductByID(c *gin.Context, productID ProductID, params DeleteProductByIDParams)
	// Get a specific product by ID
	// (GET /products/{productID})
	GetProductByID(c *gin.Context, productID ProductID, params GetProductByIDParams)
	// Update an existing product
	// (PUT /products/{productID})
	UpdateProductByID(c *gin.Context, productID ProductID, params UpdateProductByIDParams)
	// Get readiness status
	// (GET /readiness)
	GetReadiness(c *gin.Context, params GetReadinessParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCustomers operation middleware
func (siw *ServerInterfaceWrapper) GetCustomers(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCustomers(c, params)
}

// CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomer(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCustomerParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateCustomer(c, params)
}

// DeleteCustomerByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteCustomerByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "customerID" -------------
	var customerID CustomerID

	err = runtime.BindStyledParameter("simple", false, "customerID", c.Param("customerID"), &customerID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter customerID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteCustomerByIDParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCustomerByID(c, customerID, params)
}

// GetCustomerByID operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "customerID" -------------
	var customerID CustomerID

	err = runtime.BindStyledParameter("simple", false, "customerID", c.Param("customerID"), &customerID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter customerID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomerByIDParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCustomerByID(c, customerID, params)
}

// UpdateCustomerByID operation middleware
func (siw *ServerInterfaceWrapper) UpdateCustomerByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "customerID" -------------
	var customerID CustomerID

	err = runtime.BindStyledParameter("simple", false, "customerID", c.Param("customerID"), &customerID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter customerID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateCustomerByIDParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateCustomerByID(c, customerID, params)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLivenessParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLiveness(c, params)
}

// GetOrders operation middleware
func (siw *ServerInterfaceWrapper) GetOrders(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrdersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrders(c, params)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrderParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrder(c, params)
}

// DeleteOrderByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrderByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderID" -------------
	var orderID OrderID

	err = runtime.BindStyledParameter("simple", false, "orderID", c.Param("orderID"), &orderID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteOrderByIDParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteOrderByID(c, orderID, params)
}

// GetOrderByID operation middleware
func (siw *ServerInterfaceWrapper) GetOrderByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderID" -------------
	var orderID OrderID

	err = runtime.BindStyledParameter("simple", false, "orderID", c.Param("orderID"), &orderID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrderByIDParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrderByID(c, orderID, params)
}

// UpdateOrderByID operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrderByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderID" -------------
	var orderID OrderID

	err = runtime.BindStyledParameter("simple", false, "orderID", c.Param("orderID"), &orderID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateOrderByIDParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOrderByID(c, orderID, params)
}

// GetProducts operation middleware
func (siw *ServerInterfaceWrapper) GetProducts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProductsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProducts(c, params)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateProductParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProduct(c, params)
}

// DeleteProductByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteProductByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "productID" -------------
	var productID ProductID

	err = runtime.BindStyledParameter("simple", false, "productID", c.Param("productID"), &productID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteProductByIDParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteProductByID(c, productID, params)
}

// GetProductByID operation middleware
func (siw *ServerInterfaceWrapper) GetProductByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "productID" -------------
	var productID ProductID

	err = runtime.BindStyledParameter("simple", false, "productID", c.Param("productID"), &productID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProductByIDParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductByID(c, productID, params)
}

// UpdateProductByID operation middleware
func (siw *ServerInterfaceWrapper) UpdateProductByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "productID" -------------
	var productID ProductID

	err = runtime.BindStyledParameter("simple", false, "productID", c.Param("productID"), &productID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateProductByIDParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateProductByID(c, productID, params)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReadinessParams

	headers := c.Request.Header

	// ------------- Required header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = XRequestID

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter xRequestID is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/customers", wrapper.GetCustomers)
	router.POST(options.BaseURL+"/customers", wrapper.CreateCustomer)
	router.DELETE(options.BaseURL+"/customers/:customerID", wrapper.DeleteCustomerByID)
	router.GET(options.BaseURL+"/customers/:customerID", wrapper.GetCustomerByID)
	router.PUT(options.BaseURL+"/customers/:customerID", wrapper.UpdateCustomerByID)
	router.GET(options.BaseURL+"/liveness", wrapper.GetLiveness)
	router.GET(options.BaseURL+"/orders", wrapper.GetOrders)
	router.POST(options.BaseURL+"/orders", wrapper.CreateOrder)
	router.DELETE(options.BaseURL+"/orders/:orderID", wrapper.DeleteOrderByID)
	router.GET(options.BaseURL+"/orders/:orderID", wrapper.GetOrderByID)
	router.PUT(options.BaseURL+"/orders/:orderID", wrapper.UpdateOrderByID)
	router.GET(options.BaseURL+"/products", wrapper.GetProducts)
	router.POST(options.BaseURL+"/products", wrapper.CreateProduct)
	router.DELETE(options.BaseURL+"/products/:productID", wrapper.DeleteProductByID)
	router.GET(options.BaseURL+"/products/:productID", wrapper.GetProductByID)
	router.PUT(options.BaseURL+"/products/:productID", wrapper.UpdateProductByID)
	router.GET(options.BaseURL+"/readiness", wrapper.GetReadiness)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbe2/juBH/KgTbP+VY2eSKrYEDmrV9W6OB10ji3qGLIGCksc2rRGopKokb+LsXfEii",
	"LPkZ54Fk/0psUpz3zI8z8iMOeJxwBkymuPOIEyJIDBKE/tTNUsljEIOe+hRCGgiaSMoZ7uBBD/EJkjNA",
	"gd2FPUzVSkLkDHuYkRhwBwflGR4W8COjAkLckSIDD6fBDGKiDv+rgAnu4L+0S37aZjVtO2wsFh7+JsJN",
	"LHG1pZkfbp/el5mcuuJkJHiYBXI9L4nZ1MxNUpywLz8lD4qjP1oX8CODtJGnYrGl6Wl2ZkCMqixDD+Xz",
	"+3Lk8qB4imhMpXpIE/yRgZiX9Myie3QIE5JFEnc++R6WVEZq27ndJueJ+kiZhCkIvPDwQ4uThLYCHsIU",
	"WAsepCAtSabagfNTCzJ3JKIhkdoRYiohTuTcm0r41desJmQKqzjVa42MOnyOzKZ92bQ01nK5yHnQj576",
	"vvoTcCaBaS2TJIloQJTN23+myvCPWxquLwQXhkLVcb6QEFmbKllO/ePnpzlmJJMzLuj/IDRET56f6G9c",
	"3NIwBGYonj4/xSGX6DeeMS3jLy9hzAGTIBiJ0CWIOxDIbvSKbK/rgOAJCElBO1kggEgIb4isJ5WuWUNn",
	"EoUgCY1S7GF4IHGiA+KT/+m45R+3Tvwr/3PnxO/4/n+whydcxOo0rNy8JWmso8YGUXlkGUqpFJRN8YZA",
	"cgJHTIKTk5O/35QElCogJjRSOwsGzDcOcasF1M8X9mXAJk/PUFDUaaj21CjpXPvQmvKWpZVlNDwaj6vf",
	"t2iccKEtYDOS2oY9U1E6eErlLLs9CnjcnnI+jaCt1xd7cKweW+SJr4HhIYnhAJoxKXfGWTOVkV45hAGO",
	"/3aqaWVJuNKPx2btkH5cHnlgP164pfk71l7AjE1ydzZqvS7o8ts/IZBumPeslLVof90YeWdOt2Sqna3U",
	"hOO6LqTW+cEmhGIhvFLnva2kElRRvCk7Ndm+AgNBInQ2GpjKhC4gTThLlThLVYmHxoY1sBXymFDmrFkz",
	"LjwcQ5pakFdbE0Bsia0tqcBLJYmTSlxUgr76yJLdc7Ke4fq6jCWjhwYPOKd3wCBtCNCVMuwZDakkMjOh",
	"z7JYsTseYQ/3vv0+dHxz/1DgDPjk1/EI6RN1TNSkHcJ97r050twlMS3bq8giywtl5O8p1RPjegj3+gbp",
	"CLkECOEe6R054nbK0ZL/O3htm+tznvAXXn7t1Meo+0W66Ywh3NuLJi6tR4Qgc/2ZPBiWqqIYMa7UoiNE",
	"GT08u43ceunsL23KsvjWRLXkkkQrqajFXajow2pUlszqtDYKlTmxW7MVbrZ4rrqaR1ckedzBjTNG5U0i",
	"aADVhFQIu1Ys663OIU2uqiV7z5eBXQMI1yC8Mf5bxe87R/maEC9rRFP0XepV1+a2kIz6w95g+BV7+Oz3",
	"s8HVYPj1ZjTo/kvXl8Hw5uribHg5uFLFpn8++Hf/oq9U1j0bdvvn5/r/i/7V+GKo/+0NLkfjq37PjUCX",
	"PD5YqbJcoyWeUckxKvhFBbco5xUVnC7eVXJ83xeoplxf+P3K/NiEz78VLWYXnJtv3yIy5/WW9ntO+0tF",
	"tyqKlR/1ym8dmYo2b31XEwqtFov8obfe7mlWiLp+r9HEIW/nO4KbD9HX2YDV1kyiRs6Iyc1H+fdvMSMl",
	"ewy1agL+kS+8RQkfWsIZkunmMJvwvPtPTAa2F148y9iU0P/CHWX/mKrvFAvlZOqfehmdxdmMspDgWsu/",
	"ezHuIZXM9SAhRRMuzIg09YrpbeohwkLklL4KJkj1uIAGgM5GA+zhOxCpOfz4yD/yFU2eACMJxR18cnR8",
	"5Fu1aQ20Cyrq0xS0dAVDg1A3fmS32ORVBtHfm1FruaWt52YLb+M+MwbcYmNlhnmtwtI0oTT/n3Yc02yF",
	"vd1LRhV810c4l1kQQJpOsqi0qunkZHFMxNyoE5EoKs2rDKr98Tsu9Xytbgk8bTCHqb9dBxPtZJC6/vSn",
	"LzycH2zC1dAyWkqhUmSwqBnvcMPL0mZ1GxUdZQucUFoYLZovGcsoGxHE4N59naLJYAvPiab2Y9lVXZjc",
	"GIGEujl7+vv8nC9znfd2M6n7FsaTA+h0dVcbGRnWKsyIg8gmZXkbc83rq8J/EXfcNmWgNIGATmhQqBbd",
	"zg1kXZE+sgYFG4T0qjo+fL6pqndTlvFfNstYCLwuaIxREGEIHmgqKZtuk2siZwyxKpiKUcXTy8Qz6bDg",
	"cOvQ8A76ao06a/OLNYd8/+OXZoor3v6oJYLc7CgtemvWQQpVGv8wOHKddxj8+BExnemg7w3oPrgLKvjK",
	"c9/Jvc860ybg+s2+APomUWtlAPjCkNW6ZN0qpvPbDFY/sCNWoHn+WnHNGctE2H603dQt4Lh+fC9wVLyE",
	"/BxA3HjCDiicrVaMt74qvLLw/vOH1c/Mvv6WoT2ndsVws/zq+8UrudDha4LjPS93rdhQCfa7UKzNkO48",
	"elVaGJX9xw8HF1eO35/UAXQ7utYqhZI3wahR8duVNwmkCoW9LIaqkG2elu3a9Ct/JNRgIzd22o/FbGQL",
	"hGEP2StHOj8seg6UkWtql27fWi15m3LKq2vBfwkP3L3RZ7VaK8LVLLG6DL+ieg+fVXZKKf5LppT9CvLG",
	"xCKAhHRTg++i2PSzw/deQHhh+HqLrzT3tfm9oT7J2LtKrAd3EPEkBiaR2YU9nAk9tJYy6bTbEQ9INOOp",
	"7Hz2P/vaByyZ2r2zHFALiLSvS152gNzXqFKdLrZ53J1/Lv1KYvtDHAhVfXkixYvrxf8DAAD//9VRQslE",
	"PQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
