// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	uuid "github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for LivenessStatus.
const (
	DOWN LivenessStatus = "DOWN"
	UP   LivenessStatus = "UP"
)

// Defines values for OrderStatus.
const (
	AWAITINGPICKUP OrderStatus = "AWAITING_PICKUP"
	CANCELLED      OrderStatus = "CANCELLED"
	DELIVERED      OrderStatus = "DELIVERED"
	DISPUTED       OrderStatus = "DISPUTED"
	INTRANSIT      OrderStatus = "IN_TRANSIT"
	PENDING        OrderStatus = "PENDING"
	RETURNED       OrderStatus = "RETURNED"
)

// N400 Bad Request
type N400 = interface{}

// N401 Unauthorized
type N401 = interface{}

// N403 Forbidden
type N403 = interface{}

// N404 Not Found
type N404 = interface{}

// N500 Internal Server Error
type N500 = interface{}

// Customer defines model for Customer.
type Customer struct {
	// CreatedAt Created At details
	CreatedAt *time.Time          `json:"created_at,omitempty" validate:"rfc3339_date-time"`
	Email     openapi_types.Email `json:"email" validate:"required,email"`
	Id        uuid.UUID           `json:"id" validate:"required,id"`
	Name      string              `json:"name" validate:"required"`
	Phone     string              `json:"phone" validate:"required,e164"`

	// UpdatedAt Updated At details
	UpdatedAt *time.Time `json:"updated_at,omitempty" validate:"rfc3339_date-time"`
}

// CustomerDetails defines model for CustomerDetails.
type CustomerDetails struct {
	Email openapi_types.Email `json:"email" validate:"required,email"`
	Name  string              `json:"name" validate:"required"`
	Phone string              `json:"phone" validate:"required,e164"`
}

// CustomerIdType CustomerID
type CustomerIdType = uuid.UUID

// Error General API Error Response
type Error struct {
	Code      int        `json:"code"`
	Domain    *string    `json:"domain,omitempty"`
	Message   string     `json:"message"`
	Reason    *string    `json:"reason,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Liveness defines model for Liveness.
type Liveness struct {
	Message *string         `json:"message,omitempty" validate:"required"`
	Status  *LivenessStatus `json:"status,omitempty" validate:"required,oneof=UP DOWN"`
}

// LivenessStatus defines model for Liveness.Status.
type LivenessStatus string

// NewCustomerRequest defines model for NewCustomerRequest.
type NewCustomerRequest struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`
	Phone string              `json:"phone" validate:"e164"`
}

// NewOrderRequest New Order Request details
type NewOrderRequest struct {
	Customer CustomerDetails `json:"customer"`
	Products []NewProduct    `json:"products"`

	// Taxes Order Taxes details
	Taxes *float64 `json:"taxes,omitempty"`

	// Total Order Total details
	Total *float64 `json:"total,omitempty"`
}

// NewProduct defines model for NewProduct.
type NewProduct struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	UnitPrice   float64 `json:"unit_price"`
}

// Order defines model for Order.
type Order struct {
	// CreatedAt Created At details
	CreatedAt *time.Time `json:"created_at,omitempty" validate:"rfc3339_date-time"`
	Customer  Customer   `json:"customer"`
	Id        uuid.UUID  `json:"id" validate:"required,id"`
	Products  []Product  `json:"products"`

	// Status Order Status details
	Status OrderStatus `json:"status" validate:"required,oneof=PENDING AWAITING_PICKUP IN_TRANSIT DELIVERED CANCELLED RETURNED DISPUTED"`

	// Taxes Order Taxes details
	Taxes *float64 `json:"taxes,omitempty"`

	// Total Order Total details
	Total *float64 `json:"total,omitempty"`

	// UpdatedAt Updated At details
	UpdatedAt *time.Time `json:"updated_at,omitempty" validate:"rfc3339_date-time"`
}

// OrderStatus Order Status details
type OrderStatus string

// OrderIdType OrderID
type OrderIdType = uuid.UUID

// Product defines model for Product.
type Product struct {
	// CreatedAt Created At details
	CreatedAt *time.Time `json:"created_at,omitempty" validate:"rfc3339_date-time"`

	// Description Product Description details
	Description *string   `json:"description,omitempty"`
	Id          uuid.UUID `json:"id" validate:"required,id"`

	// Name Product Name details
	Name      string  `json:"name" validate:"required"`
	UnitPrice float64 `json:"unit_price"`

	// UpdatedAt Updated At details
	UpdatedAt *time.Time `json:"updated_at,omitempty" validate:"rfc3339_date-time"`
}

// ProductIdType ProductID
type ProductIdType = uuid.UUID

// XRequestIdType X-RequestID
type XRequestIdType = uuid.UUID

// CustomerID CustomerID
type CustomerID = CustomerIdType

// OrderID OrderID
type OrderID = OrderIdType

// ProductID ProductID
type ProductID = ProductIdType

// XRequestID X-RequestID
type XRequestID = XRequestIdType

// Limit defines model for limit.
type Limit = int

// Page defines model for page.
type Page = int

// GetCustomersParams defines parameters for GetCustomers.
type GetCustomersParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty" schema:"page" validate:"omitempty,gte=0"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty" schema:"limit" validate:"omitempty,gte=0"`

	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// CreateCustomerParams defines parameters for CreateCustomer.
type CreateCustomerParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// DeleteCustomerByIDParams defines parameters for DeleteCustomerByID.
type DeleteCustomerByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// GetCustomerByIDParams defines parameters for GetCustomerByID.
type GetCustomerByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// UpdateCustomerByIDParams defines parameters for UpdateCustomerByID.
type UpdateCustomerByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// GetLivenessParams defines parameters for GetLiveness.
type GetLivenessParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty" schema:"page" validate:"omitempty,gte=0"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty" schema:"limit" validate:"omitempty,gte=0"`

	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// CreateOrderParams defines parameters for CreateOrder.
type CreateOrderParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// DeleteOrderByIDParams defines parameters for DeleteOrderByID.
type DeleteOrderByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// GetOrderByIDParams defines parameters for GetOrderByID.
type GetOrderByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// UpdateOrderByIDParams defines parameters for UpdateOrderByID.
type UpdateOrderByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// GetProductsParams defines parameters for GetProducts.
type GetProductsParams struct {
	Page  *Page  `form:"page,omitempty" json:"page,omitempty" schema:"page" validate:"omitempty,gte=0"`
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty" schema:"limit" validate:"omitempty,gte=0"`

	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// CreateProductParams defines parameters for CreateProduct.
type CreateProductParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// DeleteProductByIDParams defines parameters for DeleteProductByID.
type DeleteProductByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// GetProductByIDParams defines parameters for GetProductByID.
type GetProductByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// UpdateProductByIDParams defines parameters for UpdateProductByID.
type UpdateProductByIDParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// GetReadinessParams defines parameters for GetReadiness.
type GetReadinessParams struct {
	// XRequestID X-Request-ID
	XRequestID *XRequestID `json:"xRequestID,omitempty"`
}

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = NewCustomerRequest

// UpdateCustomerByIDJSONRequestBody defines body for UpdateCustomerByID for application/json ContentType.
type UpdateCustomerByIDJSONRequestBody = Customer

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = NewOrderRequest

// UpdateOrderByIDJSONRequestBody defines body for UpdateOrderByID for application/json ContentType.
type UpdateOrderByIDJSONRequestBody = Order

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = NewProduct

// UpdateProductByIDJSONRequestBody defines body for UpdateProductByID for application/json ContentType.
type UpdateProductByIDJSONRequestBody = Product

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all customers
	// (GET /customers)
	GetCustomers(c *gin.Context, params GetCustomersParams)
	// Create a new customer
	// (POST /customers)
	CreateCustomer(c *gin.Context, params CreateCustomerParams)
	// Delete a customer
	// (DELETE /customers/{customerID})
	DeleteCustomerByID(c *gin.Context, customerID CustomerID, params DeleteCustomerByIDParams)
	// Get a specific customer by ID
	// (GET /customers/{customerID})
	GetCustomerByID(c *gin.Context, customerID CustomerID, params GetCustomerByIDParams)
	// Update an existing customer
	// (PUT /customers/{customerID})
	UpdateCustomerByID(c *gin.Context, customerID CustomerID, params UpdateCustomerByIDParams)
	// Get liveness status
	// (GET /liveness)
	GetLiveness(c *gin.Context, params GetLivenessParams)
	// Get all orders
	// (GET /orders)
	GetOrders(c *gin.Context, params GetOrdersParams)
	// Create a new order
	// (POST /orders)
	CreateOrder(c *gin.Context, params CreateOrderParams)
	// Delete an order
	// (DELETE /orders/{orderID})
	DeleteOrderByID(c *gin.Context, orderID OrderID, params DeleteOrderByIDParams)
	// Get a specific order by ID
	// (GET /orders/{orderID})
	GetOrderByID(c *gin.Context, orderID OrderID, params GetOrderByIDParams)
	// Update an existing order
	// (PUT /orders/{orderID})
	UpdateOrderByID(c *gin.Context, orderID OrderID, params UpdateOrderByIDParams)
	// Get all products
	// (GET /products)
	GetProducts(c *gin.Context, params GetProductsParams)
	// Create a new product
	// (POST /products)
	CreateProduct(c *gin.Context, params CreateProductParams)
	// Delete a product
	// (DELETE /products/{productID})
	DeleteProductByID(c *gin.Context, productID ProductID, params DeleteProductByIDParams)
	// Get a specific product by ID
	// (GET /products/{productID})
	GetProductByID(c *gin.Context, productID ProductID, params GetProductByIDParams)
	// Update an existing product
	// (PUT /products/{productID})
	UpdateProductByID(c *gin.Context, productID ProductID, params UpdateProductByIDParams)
	// Get readiness status
	// (GET /readiness)
	GetReadiness(c *gin.Context, params GetReadinessParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCustomers operation middleware
func (siw *ServerInterfaceWrapper) GetCustomers(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCustomers(c, params)
}

// CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomer(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateCustomerParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateCustomer(c, params)
}

// DeleteCustomerByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteCustomerByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "customerID" -------------
	var customerID CustomerID

	err = runtime.BindStyledParameter("simple", false, "customerID", c.Param("customerID"), &customerID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter customerID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteCustomerByIDParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCustomerByID(c, customerID, params)
}

// GetCustomerByID operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "customerID" -------------
	var customerID CustomerID

	err = runtime.BindStyledParameter("simple", false, "customerID", c.Param("customerID"), &customerID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter customerID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomerByIDParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCustomerByID(c, customerID, params)
}

// UpdateCustomerByID operation middleware
func (siw *ServerInterfaceWrapper) UpdateCustomerByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "customerID" -------------
	var customerID CustomerID

	err = runtime.BindStyledParameter("simple", false, "customerID", c.Param("customerID"), &customerID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter customerID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateCustomerByIDParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateCustomerByID(c, customerID, params)
}

// GetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetLiveness(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLivenessParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLiveness(c, params)
}

// GetOrders operation middleware
func (siw *ServerInterfaceWrapper) GetOrders(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrdersParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrders(c, params)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateOrderParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrder(c, params)
}

// DeleteOrderByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrderByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderID" -------------
	var orderID OrderID

	err = runtime.BindStyledParameter("simple", false, "orderID", c.Param("orderID"), &orderID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteOrderByIDParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteOrderByID(c, orderID, params)
}

// GetOrderByID operation middleware
func (siw *ServerInterfaceWrapper) GetOrderByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderID" -------------
	var orderID OrderID

	err = runtime.BindStyledParameter("simple", false, "orderID", c.Param("orderID"), &orderID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOrderByIDParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrderByID(c, orderID, params)
}

// UpdateOrderByID operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrderByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "orderID" -------------
	var orderID OrderID

	err = runtime.BindStyledParameter("simple", false, "orderID", c.Param("orderID"), &orderID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orderID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateOrderByIDParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOrderByID(c, orderID, params)
}

// GetProducts operation middleware
func (siw *ServerInterfaceWrapper) GetProducts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProductsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProducts(c, params)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateProductParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProduct(c, params)
}

// DeleteProductByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteProductByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "productID" -------------
	var productID ProductID

	err = runtime.BindStyledParameter("simple", false, "productID", c.Param("productID"), &productID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteProductByIDParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteProductByID(c, productID, params)
}

// GetProductByID operation middleware
func (siw *ServerInterfaceWrapper) GetProductByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "productID" -------------
	var productID ProductID

	err = runtime.BindStyledParameter("simple", false, "productID", c.Param("productID"), &productID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProductByIDParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProductByID(c, productID, params)
}

// UpdateProductByID operation middleware
func (siw *ServerInterfaceWrapper) UpdateProductByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "productID" -------------
	var productID ProductID

	err = runtime.BindStyledParameter("simple", false, "productID", c.Param("productID"), &productID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter productID: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateProductByIDParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateProductByID(c, productID, params)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReadinessParams

	headers := c.Request.Header

	// ------------- Optional header parameter "xRequestID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("xRequestID")]; found {
		var XRequestID XRequestID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for xRequestID, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "xRequestID", runtime.ParamLocationHeader, valueList[0], &XRequestID)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter xRequestID: %w", err), http.StatusBadRequest)
			return
		}

		params.XRequestID = &XRequestID

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/customers", wrapper.GetCustomers)
	router.POST(options.BaseURL+"/customers", wrapper.CreateCustomer)
	router.DELETE(options.BaseURL+"/customers/:customerID", wrapper.DeleteCustomerByID)
	router.GET(options.BaseURL+"/customers/:customerID", wrapper.GetCustomerByID)
	router.PUT(options.BaseURL+"/customers/:customerID", wrapper.UpdateCustomerByID)
	router.GET(options.BaseURL+"/liveness", wrapper.GetLiveness)
	router.GET(options.BaseURL+"/orders", wrapper.GetOrders)
	router.POST(options.BaseURL+"/orders", wrapper.CreateOrder)
	router.DELETE(options.BaseURL+"/orders/:orderID", wrapper.DeleteOrderByID)
	router.GET(options.BaseURL+"/orders/:orderID", wrapper.GetOrderByID)
	router.PUT(options.BaseURL+"/orders/:orderID", wrapper.UpdateOrderByID)
	router.GET(options.BaseURL+"/products", wrapper.GetProducts)
	router.POST(options.BaseURL+"/products", wrapper.CreateProduct)
	router.DELETE(options.BaseURL+"/products/:productID", wrapper.DeleteProductByID)
	router.GET(options.BaseURL+"/products/:productID", wrapper.GetProductByID)
	router.PUT(options.BaseURL+"/products/:productID", wrapper.UpdateProductByID)
	router.GET(options.BaseURL+"/readiness", wrapper.GetReadiness)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbW/juBH+KwTbj3KsbHLF1sABzca+rdHAayRx79BFEDDS2OZVIrUUlcQN/N8LkhJF",
	"WfLr2s4i2U+JRYoznNeHM9QLDniccAZMprjzghMiSAwShP51maWSxyD6XfUrhDQQNJGUM9zB/S7iYySn",
	"gIJ8FvYwVSMJkVPsYUZiwB0clGt4OA2mEBO12F8FjHEH/6Vd0m+b0bTtkJ3PPfxFhOtY4GpKM32ev70p",
	"8YKaojwUPMwCuZp2YiY1U0/sCpvSL2kqDv5oXcO3DNJGHuxgS6+vyU+BGFHkDDyX72/KgUtT8RDRmEr1",
	"kibwLQMxK9c3g+7SIYxJFknc+eB7WFIZqWlX+TQ5S9RPyiRMQOC5h59bnCS0FfAQJsBa8CwFaUky0QZY",
	"rGrJPJKIhkRqxcZUQpzImTeR8KuvWU3IBJZxqscaGXX4HJpJu7KZ01jJ5bzgQb967vvqT8CZBKalTJIk",
	"ogFROm7/mSpFv2youJ4QXBgKVUP5REKU61Tt5dw/PTzNESOZnHJB/wehIXp2eKK/cfFAwxCYoXh+eIoD",
	"LtFvPGN6j78cQ5l9JkEwEqEbEI8gUD7Rs9Fax3HBExCSgjayQACREN4TWQ8il2YMXUgUgiQ0SrGH4ZnE",
	"iXaID/6H05Z/2jrzb/2PnTO/4/v/wR4ecxGr1bAy85aksfaa3InKJUtXSqWgbILXOJLjOGIcnJ2d/f2+",
	"JKBEATGhkZppGTBPHOK5FFCvGNiVAfiWUQGhZygo6jRUc2qUdGx9bk14K6eVZTQ8GY2qz1s0TrjQGsgj",
	"kpqGPZMxOnhC5TR7OAl43J5wPomgrcfnO3CsXpsXga+B4QGJYQ+SMSF3ylkzlaEe2YcCTv92rmllSbjU",
	"jkdmbJ92XC65Zzuee6UMO1+xtgJmdFKYsxHrnaXLH/6EQLpu3s13WfP21/WRN2Z0C6raWktNuO3ShcQ6",
	"PuQBwQ6Et2q9AwaVuYdN3qgx9xkYCBKhi2HfpBZ0DWnCWar4WUgrPDRKqKGlkMeEMmcs18PcwzGkaY7S",
	"amMCSJ4ja0PKc1JJ4qRi2BWvrb6yoLiCrGe4viudwcihQYVX9BEYpA0etnQPO5pzKonMjO+yLFbsjobY",
	"w90vvw8c49rdljkDPv51NER6RW3Utd0O4KkwvwIqbhNZFvVlw8DiQOm6O+7qOx1zAE/6iOdscgHRwRPS",
	"MwrI7OSTBft3ANcm59kiYs+94lyol1EHhHTdGgN4yk+GuNQeEYLM9G/ybFiqbsVs41YNOpsovYdnD5Gb",
	"8Jz5pU5ZFj8Yr5ZckmgpFTW4DRW9WI3Kglqd2oIVmeO7NV3hZo0XoqtZdGUnL1uYccaovE8EDaAakOxm",
	"V24rt1ZnkSZT1Tt7y2h+WwfCNQxulP+jAvCtvXyFi5c5osn7bvSoq/M8kQx7g25/8Bl7+OL3i/5tf/D5",
	"fti//JfOL/3B/e31xeCmf6uSTe+q/+/edU+J7PJicNm7utL/X/duR9cD/W+3fzMc3fa6rge65PHeUlXO",
	"NVrgGZUcI8svstyigldkOZ2/qeD4tk9ATbHe2v3S+NgEsL/Ymq+Lrs3TY0Drpenm7YTuhcRZ3Uq+f9Qt",
	"nzp7srXW+qwmJFkN+MVLP3rNpVkg6gy8QhL7PCJvCVDeRXFlDd5a0e4ZOn0cN6YUz48RVTbrBdVY/KMY",
	"ODiPm+vNdkWUvpSPszEvKufEBM78rImnGZsQ+l94pOwfE/VM0S27Ov/Uw+gizqaUhQTXyuWX16MuUjFY",
	"F+FTNObCtAtTz3YuUw8RFiIn61TScapL7TQAdDHsYw8/gkjN4qcn/omvaPIEGEko7uCzk9MTP5eV3nbb",
	"UlG/JqB3Zxnqh7rmIi/tJK/ShP3aDBjLKW3dc5p7a+eZFtoGEyv9vzvlTab+o/n/sGWLYyPY6+L7Ku6t",
	"tz9usiCANB1nUalVU0TJ4piImREnIlFUqlcpVBvhV1zK+U4BdJ42qMOkzUsHjmylkLr89K9PPJztrTvU",
	"UK1ZiHxSZDCvKW9/jb9SZ3Ud2WpsjndQapUWzRaUZYSNCGLw5F4laFLY3HO8qf1SXi2Ym4AYgYS6Orv6",
	"ebHOp5kOdtup1L2R8N0OdL68IozMHlYKzGwHkXXC8tbGmtcXhX8Uc9w0ZKA0gYCOaWBFix5mBmkuCR9Z",
	"g4ANsHlVGe8/3lTFuy7K+MeNMjlyXeU0RimIMATPNJWUTTaJNZHTAVjmTLZL8P1p4kAytBxu7BreXq+l",
	"qLXWX0rZ592JX5opLrk5UQsEhdpRastauYFYURr7MDhylXUY/PgeMZ0pXu8M6N65CSr4ygvbKawvN6Z1",
	"wPVLfhnyh0Stld7bkSFrbpJ1rZiiazNYfceGWIHmxRXbmjGWgbD9kl+23QCO69d3Akf2gu4hgLixhC1Q",
	"OFsuGG91VnjlzfuHd6ufkX31KUNbTu2I4Ub55eeLVzKh/ecEx3qOd6xYkwl2O1CsjJBuK3hZWBiW9cd3",
	"BxeXdr6/qwLoVnRzrVghr4NRQ/tdxw8JpKzAjouhKmSbm1zbFv3KD2gadOT6TvvFfk6zAcLIF9kpRjof",
	"4RwCZRSS2qbat1JK3rqY8upS8I9hgdsX+nKp1pJwNUosT8OvKN79R5WtQop/zJCyW0JeG1gEkJCuK/Bd",
	"20k/K3xvBYRbxddLfKW678y3enolo+8qsS48QsSTGJhEZhb2cCZ001rKpNNuRzwg0ZSnsvPR/+hrG8jJ",
	"1M6dZYNaQKRtXfKyAuTeYEp1uNjkdbf/ufCFweaLOBCqeuchxfO7+f8DAAD//7S+xR5APAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
