name: Audit

on:
  push:
    branches:
      - '**'

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Verify Orders dependencies
        run: | 
          cd  orders
          go mod verify

      - name: Verify Payments dependencies
        run: | 
          cd  payments
          go mod verify

      - name: Build Orders
        run: | 
          cd orders
          go build -v ./...

      - name: Build Payments
        run: | 
          cd payments
          go build -v ./...

      - name: Run go vet Orders
        run: |
          cd orders
          go vet ./...

      - name: Run go vet Payments
        run: |
          cd payments
          go vet ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint Orders
        run: |
          cd orders
          golint ./...

      - name: Run golint Payments
        run: |
          cd payments
          golint ./...

      - name: Run Order tests
        run: | 
          cd orders
          go test -race -vet=off ./...

      - name: Run Payments tests
        run: | 
          cd payments 
          go test -race -vet=off ./...