name: Audit

on: [pull_request]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Verify Orders dependencies
        working-directory: ./orders
        run: | 
          cd ./orders
          go mod verify

      - name: Build Orders
        working-directory: ./orders
        run: | 
          cd ./orders
          go build -v ./...

      - name: Run go vet Orders
        working-directory: ./orders
        run: |
          cd ./orders
          go vet ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        working-directory: ./orders
        run: |
          cd ./orders
          
          golint ./...

      - name: Run tests
        working-directory: ./orders
        run: | 
          cd ./orders
          
          go test -race -vet=off ./...